[project]
name = "dum-e"
version = "0.1.0"
description = "The Software System of a Dum-E Replica"
readme = "README.md"
authors = [
    { name = "Ayush Manoj", email = "ayushmanoj279@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pybullet>=3.2.6",
    "pyyaml>=6.0",
    "pytest>=9.1.1",
]

[project.scripts]
dum-e = "dum_e:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
